services:
  app:
    container_name: rest-api
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: "always"
    environment:
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: moneytransfer
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    restart: "always"



volumes:
  pgdata: